name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Create .env file
      run: |
        echo "STRAPI_TOKEN=${{ secrets.STRAPI_TOKEN }}" >> .env
        echo "STRAPI_HOST=${{ secrets.STRAPI_HOST }}" >> .env

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to Server using SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./"
        target: "/srv/www/html/"

    - name: Run remote commands
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          export STRAPI_TOKEN=${{ secrets.STRAPI_TOKEN }}
          export STRAPI_HOST=${{ secrets.STRAPI_HOST }}

          cd /srv/www/html
          npm install
          pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
        EOF
